baseURL = 'https://www.shantanualshi.com/'
languageCode = 'en-us'
title = 'Shantanu Alshi'
theme = 'mini'
googleAnalytics = 'G-C6SNRYL17D'

[params]
    hiddenPostSummaryInHomePage = true
    enableGoogleAnalytics = true