baseURL = 'https://www.shantanualshi.com/'
languageCode = 'en-us'
title = 'Shantanu Alshi'
theme = 'paper'
googleAnalytics = 'G-C6SNRYL17D'

[params]
    hiddenPostSummaryInHomePage = true
    enableGoogleAnalytics = true
    color = 'light'
    math = true